# Project with ReactJS

# Use Node image for Docker
image: node:10.22.0

before_script:
  - cat /proc/sys/fs/inotify/max_user_watches 
  - sysctl fs.inotify.max_user_watches=524288
  - cat /proc/sys/fs/inotify/max_user_watches 
  - npm install

# Apply settings for job 'pages'
pages:
  stage: deploy
  script:
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules/
  only:
    - master # Run deploy only when 'master' branch

## After deploy, page can be accessed by URL
## https://brunoleocoelho.gitlab.io/interface-web-biblioteca-tcc/