# Project with ReactJS

# Use Node image for Docker
image: node:10.22.0

cache:
  paths:
    - node_modules/

before_script:
  - cat /proc/sys/fs/inotify/max_user_watches 
  - sysctl fs.inotify.max_user_watches=524288
  - npm cache clean --force
  - CI=false npm install

pages:
  stage: deploy
  script:
    - CI=false npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master # Run deploy only when 'master' branch

after_script:
  - rm -rf node_modules

## After deploy, page can be accessed by URL
## https://brunoleocoelho.gitlab.io/interface-web-biblioteca-tcc/