// BookFilters
export const AUTHOR_SET_FILTER = 'AUTHOR_SET_FILTER'
export const CATEGORY_SET_FILTER = 'CATEGORY_SET_FILTER'
export const CLEAN_FILTERS = 'CLEAN_FILTERS'

// Books
export const BOOKS_SET_ALL = 'BOOKS_SET_ALL'
export const AUTHORS_SET_ALL = 'AUTHORS_SET_ALL'
export const CATEGORIES_SET_ALL = 'CATEGORIES_SET_ALL'
export const BOOKS_SET_LASTREAD = 'BOOKS_SET_LASTREAD'
export const BOOKS_SET_DELIVER = 'BOOKS_SET_DELIVER'
export const BOOKS_SET_RESERVED = 'BOOKS_SET_RESERVED'
export const BOOKS_SET_FAVORITE = 'BOOKS_SET_FAVORITE'

// Getinfo
export const GETINFO_BOOK = 'GETINFO_BOOK'
export const GETINFO_AUTHOR = 'GETINFO_AUTHOR'
export const GETINFO_CLEAN = 'GETINFO_CLEAN'
